smartclass/faq_video_portal/urls.py
from django.urls import re_path

from .views.course_views import *
from .views.topic_views import *
from .views.faq_views import *

urlpatterns = [
    re_path(r'^add-course/$', add_course, name='add_course'),
    re_path(r'^add-topic/$', add_topic, name='add_topic'),
    re_path(r'^add-faq/$', add_faq, name='add_faq'),
    re_path(r'^courses/(?P<id>\d+)/(?P<slug>[-\w\d]+)/$', course_home, name='course_home'),
    re_path(r'^topics/(?P<id>\d+)/(?P<slug>[-\w\d]+)/$', topic_home, name='topic_home'),
    re_path(r'^faqs/(?P<id>\d+)/(?P<slug>[-\w\d]+)/$', faq_home, name='faq_home'),
    re_path(r'^ajax/validate-course-no/$', validate_course_no, name='validate_course_no'),
    re_path(r'^ajax/validate-course-name/$', validate_course_name, name='validate_course_name'),
    re_path(r'^ajax/validate-topic/$', validate_topic, name='validate_topic'),
    re_path(r'^ajax/validate-faq/$', validate_faq, name='validate_faq'),
    re_path(r'^api/faqs/like/(?P<id>\d+)/$', FAQLikeToggleAPI.as_view(), name='faq_like_toggle_api'),
    re_path(r'^api/topics/like/(?P<id>\d+)/$', TopicLikeToggleAPI.as_view(), name='topic_like_toggle_api')
]

smartclass/smartclass/urls.py
from django.contrib import admin
from django.urls import re_path, include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import welcome, search_anything, full_search_results_display

urlpatterns = [
    re_path(r'^$', welcome, name="smartclass_welcome"),
    re_path(r'search-everything/$', search_anything, name="search_everything"),
    re_path(r'search-results/$', full_search_results_display, name="search_results"),
    path('admin/', admin.site.urls),
    path('', include('faq_video_portal.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Smart Class Admin Panel'
admin.site.site_title = 'Smart Class Panel'
admin.site.index_title = 'Welcome to Smart Class Admin Panel'

smartclass/users/urls.py
from django.urls import re_path
from django.contrib.auth.views import LoginView, LogoutView

from .views import signup, home, validate_username, change_password, author_home


urlpatterns = [
    re_path(r'^home/$', home, name="user_home"),
    re_path(r'^login/$', LoginView.as_view(template_name='users/login_form.html'), name='user_login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='user_logout'),
    re_path(r'^signup/$', signup, name='user_signup'),
    re_path(r'^change-password/$', change_password, name='user_change_password'),
    re_path(r'^author-home/(?P<id>\d+)$', author_home, name='author_home'),
    re_path(r'^ajax/validate-username/$', validate_username, name='validate_username'),
]

smartclass/faq_video_portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models import Q
from django.db.models import Value
from django.db.models.functions import Concat

from operator import or_
from functools import reduce

DIFFICULTY_LEVELS = (
    ('1', 'Beginner'),
    ('2', 'Intermediate'),
    ('3', 'Advance'),
    ('4', 'Expert'),
)


class VideoQuerySet(models.QuerySet):
    def video_search(self, search_text):
        topic = self.annotate(added_by_full_name=Concat('added_by__first_name', Value(' '), 'added_by__last_name'))
        return topic.filter(
            Q(title__icontains=search_text) |
            Q(hash_tags__icontains=search_text) |
            Q(video_keywords__icontains=search_text) |
            ((Q(added_by__first_name__startswith=search_text) |
              Q(added_by__last_name__startswith=search_text) |
              Q(added_by_full_name__startswith=search_text)) &
             Q(added_by__is_staff=True))
        ).order_by('difficulty_level')

    def faq_for_this_course(self, topics):
        return self.filter(
            Q(topic__in=topics)
        )

    def faq_search(self, search_text):
        faq = self.annotate(added_by_full_name=Concat('added_by__first_name', Value(' '), 'added_by__last_name'))
        return faq.filter(
            Q(title__icontains=search_text) |
            Q(hash_tags__icontains=search_text) |
            Q(video_keywords__icontains=search_text) |
            ((Q(added_by__first_name__startswith=search_text) |
              Q(added_by__last_name__startswith=search_text) |
              Q(added_by_full_name__startswith=search_text)) &
             Q(added_by__is_staff=True))
        )

    def related_videos(self, hash_tags):
        current_video_tags = hash_tags.strip().split(',')
        condition = reduce(or_, [Q(hash_tags__contains=tags) for tags in current_video_tags])
        return self.filter(condition)


class CourseQuerySet(models.QuerySet):
    def course_search(self, search_text):
        course = self.annotate(created_by_full_name=Concat('created_by__first_name', Value(' '),
                                                           'created_by__last_name'))
        return course.filter(
            Q(course_no__contains=search_text) |
            Q(course_name__contains=search_text) |
            Q(hash_tags__contains=search_text) |
            ((Q(created_by__first_name__startswith=search_text) |
              Q(created_by__last_name__startswith=search_text) |
              Q(created_by_full_name__startswith=search_text)) &
             Q(created_by__is_staff=True))
        ).order_by('-created_on')

    def related_courses(self, hash_tags):
        current_course_tags = hash_tags.strip().split(',')
        condition = reduce(or_, [Q(hash_tags__contains=tags) for tags in current_course_tags])
        return self.filter(condition)


class Course(models.Model):
    course_no = models.CharField(max_length=5,
                                 verbose_name="Course number",
                                 help_text="Please add a course number for this course.",
                                 blank=False,
                                 null=False)
    course_name = models.CharField(max_length=75,
                                   verbose_name="Course name",
                                   help_text="Please add a course name for this course.",
                                   blank=False,
                                   null=False)
    created_by = models.ForeignKey(User,
                                   verbose_name="Name of the instructor",
                                   on_delete=models.CASCADE)
    course_description = models.TextField(max_length=1000, verbose_name="Course description",
                                          help_text="Please add a description for this course.")
    hash_tags = models.CharField(max_length=150,
                                 verbose_name="Tags",
                                 help_text="Please add some tags separated by commas for"
                                           " better search capabilities. "
                                           " e.g. Programming, Design, Data Science, Neural Networks ",
                                 blank=False,
                                 null=False)
    course_keywords = models.TextField(verbose_name="Keywords for this course",
                                       help_text="This is generated off of the file(s) input by the user.", blank=True,
                                       default="")
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(default='',
                            editable=False)
    objects = CourseQuerySet.as_manager()

    def __str__(self):
        return "{0} - {1}".format(self.course_no, self.course_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.course_name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('course_home', kwargs={'slug': self.slug, 'id': self.id})


class VideoInfo(models.Model):
    title = models.CharField(max_length=150,
                             blank=False,
                             null=False)
    added_by = models.ForeignKey(User,
                                 verbose_name="Name of the instructor",
                                 on_delete=models.CASCADE)
    video_description = models.TextField(max_length=1000, verbose_name="Description",
                                         help_text="Please add a description for this video.")
    video_url = models.CharField(max_length=500,
                                 verbose_name="URL for the video",
                                 help_text="This is generated automatically after the video file is "
                                           "uploaded by the user.",
                                 blank=False,
                                 null=False)
    hash_tags = models.CharField(max_length=150,
                                 verbose_name="Tags",
                                 help_text="Please add some tags separated by commas for better search"
                                           " capabilities. e.g. Programming, Design, Data Science, Neural Networks ",
                                 blank=False,
                                 null=False)
    video_keywords = models.TextField(verbose_name="Keywords for this video",
                                      help_text="This is generated off of the video and the index files"
                                                " input by the user.")
    video_thumbnail_url = models.CharField(max_length=500,
                                           verbose_name="URL for the video thumbnail",
                                           help_text="This is generated automatically after the video file"
                                                     " is uploaded by the user.",
                                           blank=False,
                                           null=False)
    video_length = models.CharField(max_length=12,
                                    verbose_name="Length of the video.",
                                    blank=False,
                                    null=False,
                                    help_text="This field is filled automatically after the video "
                                              "is uploaded by the user.")
    added_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    slug = models.SlugField(default='',
                            editable=False)
    objects = VideoQuerySet.as_manager()

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return "{0}".format(self.title)


class FrequentlyAskedQuestion(VideoInfo):
    title = models.CharField(max_length=200,
                             blank=False,
                             null=False,
                             verbose_name="Question",
                             help_text="Please add a question."
                                       "(Should be less than 150 characters.)")
    views = models.ManyToManyField(User,
                                   related_name="view_count_faq",
                                   blank=True)
    likes = models.ManyToManyField(User,
                                   related_name="liked_users_faq",
                                   blank=True)

    def get_absolute_url(self):
        return reverse('faq_home', kwargs={'slug': self.slug, 'id': self.id})

    def get_api_like_url(self):
        return reverse('faq_like_toggle_api', kwargs={'id': self.id})


class Topic(VideoInfo):
    title = models.CharField(max_length=150,
                             blank=False,
                             null=False,
                             verbose_name="Topic Name",
                             help_text="Please add a topic name for this video. "
                                       "(Should be less than 150 characters.)")

    associated_courses = models.ManyToManyField(Course,
                                                verbose_name="Courses associated with this video.",
                                                help_text="Select all the courses that you want to "
                                                          "associate this topic with.")
    associated_faqs = models.ManyToManyField(FrequentlyAskedQuestion,
                                             verbose_name="FAQs associated with this video.",
                                             help_text="(Optional) Select all the FAQs that you want to "
                                                       "associate this topic with.",

smartclass/faq_video_portal/forms.py
from django.forms import ModelForm

from .models import Course, Topic, FrequentlyAskedQuestion


class CourseForm(ModelForm):
    class Meta:
        model = Course
        exclude = ('course_keywords', 'created_by', 'created_on', 'slug')

    def clean_course_no(self):
        return self.cleaned_data['course_no'].upper()

    def clean_course_name(self):
        return self.cleaned_data['course_name'].title()


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['title', 'video_description', 'difficulty_level', 'hash_tags', 'associated_courses',
                  'associated_faqs']
        exclude = ('video_keywords', 'added_by', 'added_on', 'video_url', 'video_thumbnail_url', 'video_length',
                   'modified_on', 'views', 'likes', 'slug')

    def clean_title(self):
        return self.cleaned_data['title'].title()

    def clean_video_description(self):
        return self.cleaned_data['video_description'].capitalize()


class FAQForm(ModelForm):
    class Meta:
        model = FrequentlyAskedQuestion
        fields = ['title', 'video_description', 'hash_tags']
        exclude = ('video_keywords', 'added_by', 'added_on', 'video_url', 'video_thumbnail_url', 'video_length',
                   'modified_on', 'views', 'likes', 'slug')

        def clean_title(self):
            return self.cleaned_data['title'].title()

        def clean_video_description(self):
            return self.cleaned_data['video_description'].capitalize()

smartclass/templates/faq_video_portal/forms/add_course_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
New Course
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <h2>Please fill in the details of your new course.</h2>
        <form id="id_valid_form" method="post" action="{% url 'add_course' %}" autocomplete="off" enctype="multipart/form-data"
              data-validate-course-no-url="{% url 'validate_course_no' %}" data-validate-course-name-url="{% url 'validate_course_name' %}">
            {% csrf_token %}

            {{ form | crispy }}

            <label for="image-uploads" style="margin-bottom: 10px">Upload Index Files</label>
            <input id="image-uploads" style="margin-bottom: 10px" type="file" name="index_files" accept=".jpg,.jpeg,.png" multiple>
            <p id="hint_id_image_uploads" class="help-block">(Optional) Please add index files for automatic keywords extraction.</p>

            <button type="submit" id="id_btn_submit" class="btn btn-success">Create</button>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script>
    $('#id_btn_submit').click(function(){
        return confirmDialog('Are you sure you want to add this course?');
    });
    $("#id_course_no").change(function () {
        let form = $(this).closest("form");
        ajax_validate("#id_course_no", "data-validate-course-no-url", form);
    });
    $("#id_course_name").change(function () {
        let form = $(this).closest("form");
        ajax_validate("#id_course_name", "data-validate-course-name-url", form);
    });
    </script>
{% endblock %}

smartclass/templates/faq_video_portal/forms/add_faq_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    New FAQ
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <h2>Please fill in the details of your new frequently asked question (FAQ).</h2>
        <form id="id_valid_form" method="post" action="{% url 'add_faq' %}" autocomplete="off"
              data-validate-question-url="{% url 'validate_faq' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy }}

            <label for="image-uploads" style="margin-bottom: 10px">Upload Index Files</label>
            <input id="image-uploads" style="margin-bottom: 10px" type="file" name="index_files" accept=".jpg,.jpeg,.png" multiple>
            <p id="hint_id_image_uploads" class="help-block">(Optional) Please add index files for automatic keyword extraction.</p>

            <label for="video-upload" class="control-label requiredField" style="margin-bottom: 10px">Upload Video<span class="asteriskField">*</span></label>
            <input id="video-upload" style="margin-bottom: 10px" type="file" name="video_file" accept=".avi,.mp4,.wmv,.flv,.mov" required>
            <p id="hint_id_video_upload" class="help-block">Please upload your video.</p>

            <button type="submit" id="id_btn_submit" class="btn btn-success">Submit</button>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script>
    $('#id_btn_submit').click(function(){
        return confirmDialog('Are you sure you want to add this topic?');
    });
    $('#id_difficulty_level').addClass('selectpicker');
    $("#id_title").change(function () {
        let form = $(this).closest("form");
        ajax_validate("#id_title", "data-validate-question-url", form);
    });
    </script>
{% endblock %}

smartclass/templates/faq_video_portal/forms/add_topic_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    New Topic
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <h2>Please fill in the details of your new topic.</h2>
        <form id="id_valid_form" method="post" action="{% url 'add_topic' %}" autocomplete="off"
              data-validate-topic-url="{% url 'validate_topic' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy }}

            <label for="image-uploads" style="margin-bottom: 10px">Upload Index Files</label>
            <input id="image-uploads" style="margin-bottom: 10px" type="file" name="index_files" accept=".jpg,.jpeg,.png" multiple>
            <p id="hint_id_image_uploads" class="help-block">(Optional) Please add index files for automatic keyword extraction.</p>

            <label for="video-upload" class="control-label requiredField" style="margin-bottom: 10px">Upload Video<span class="asteriskField">*</span></label>
            <input id="video-upload" style="margin-bottom: 10px" type="file" name="video_file" accept=".avi,.mp4,.wmv,.flv,.mov" required>
            <p id="hint_id_video_upload" class="help-block">Please upload your video.</p>

            <button type="submit" id="id_btn_submit" class="btn btn-success">Submit</button>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script>
    $('#id_associated_courses').removeClass('selectmultiple').addClass('selectpicker').attr({
        'data-selected-text-format': 'count > 3',
        'data-actions-box': true,
        'data-live-search': true
    });
    $('#id_associated_faqs').removeClass('selectmultiple').addClass('selectpicker').attr({
        'data-selected-text-format': 'count > 3',
        'data-actions-box': true,
        'data-live-search': true
    });
    $('#id_btn_submit').click(function(){
        return confirmDialog('Are you sure you want to add this topic?');
    });
    $('#id_difficulty_level').addClass('selectpicker');
    $("#id_title").change(function () {
        let form = $(this).closest("form");
        ajax_validate("#id_title", "data-validate-topic-url", form);
    });
    </script>
{% endblock %}